version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '10:00'
      timezone: 'Asia/Tokyo'
    target-branch: 'main'
    open-pull-requests-limit: 10
    reviewers:
      - 'ryoqn'
