name: publish decode-sensor-data

env:
  CI: true
  TZ: 'Asia/Tokyo'

on:
  push:
    branches:
      - main
    tags:
      - '!*'

jobs:
  publish:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      # checkout
      - name: checkout
        uses: actions/checkout@v2
      # node 14.x setup
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: https://npm.pkg.github.com
      # install node modules
      - name: install node_modules
        run: npm install
      # jest
      - name: jest
        run: npm run test
      - name: uplocad test coverage
        uses: actions/upload-artifact@v1
        with:
          name: coverage
          path: coverage
      # publish pkg
      - name: publish
        run: npx can-npm-publish --verbose && npm publish || echo "No need to publish"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # set ver
      - name: set version to env
        run: node -p -e '`VERSION=${require("./package.json").version}`' >> $GITHUB_ENV
      # add tag that has version info
      - name: add verion tag
        uses: pkgdeps/git-tag-action@v2
        with:
          version: ${{ env.VERSION }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repo: ${{ github.repository }}
          git_commit_sha: ${{ github.sha }}
          git_tag_prefix: 'v'
